version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-wp
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Pet
      MYSQL_USER: sherry
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
  
    volumes:
      - ./data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-wp
    ports:
      - "8082:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-wp
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - mysql